# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe956c3ce21bf24e2b73cfc67811312906ad76975fb3f7ec461b415f3ddc14c8df10d3c8d1142c67d77b0867e7b4cf3722981f46832c329a9d8115aeccf1c34

test:
  secret_key_base: cf96357602716b7ca5f7a1d49279784974bb02c3c3bad61d29c42b29003f719757b42587b765c9ccf31ee27554732fa0a758ce064aa7c20e6a0c43fde366ebc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
